//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.AptitudeAnswers = new HashSet<AptitudeAnswer>();
            this.JobApplications = new HashSet<JobApplication>();
        }
    
        public int CandidateId { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AptiResult { get; set; }
        public Nullable<int> SSC_Marks { get; set; }
        public Nullable<int> HSC_Marks { get; set; }
        public Nullable<int> UG_Marks { get; set; }
        public Nullable<int> SkillsID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AptitudeAnswer> AptitudeAnswers { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApplication> JobApplications { get; set; }
    }
}
