//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public int InterviewID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Remark { get; set; }
    
        public virtual JobApplication JobApplication { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Status Status { get; set; }
    }
}
