//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobApplication()
        {
            this.Interviews = new HashSet<Interview>();
        }
    
        public int ApplicationId { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> JobId { get; set; }
        public string Resume { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string AbleToReallocation { get; set; }
        public string PrevCompanyName { get; set; }
        public Nullable<int> WorkExperience { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interview> Interviews { get; set; }
        public virtual JobPost JobPost { get; set; }
        public virtual Status Status { get; set; }
    }
}
