//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication
    {
        public int Application { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
        public Nullable<int> sscMarks { get; set; }
        public Nullable<int> hscMarks { get; set; }
        public Nullable<int> ugMarks { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Usr Usr { get; set; }
    }
}
